Insert / Delete/ Append 

In [5]:
import numpy as np


A = np.array([
    [1,2,3],
    [10,20,30],
    [100,200,300]
])


In [ ]:
#insert 
#axis => 0 > row
# axis => 1 > column 
np.insert(A,0,[1000,2000,3000], axis = 0)


array([[1000, 2000, 3000],
       [   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300]])

In [11]:
np.insert(A,0, [101,102,103], axis = 1)

array([[101,   1,   2,   3],
       [102,  10,  20,  30],
       [103, 100, 200, 300]])

In [12]:
#delete row
np.delete(A,0,axis = 0)


array([[ 10,  20,  30],
       [100, 200, 300]])

In [13]:
np.delete(A,1,axis = 1)

array([[  1,   3],
       [ 10,  30],
       [100, 300]])