Stacking 

In [ ]:
# Horizontal Stack >> hstack
# Vertical Stack >> vstack

import numpy as np


A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])


print(np.hstack((A,B)))
print(np.vstack((A,B)))


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# column stack 
# Diff between hstack & column stack is last array can be 1D array but in hsatck it should be 2D array

ar1 = np.array([[1,2,3], [4,5,6]])
ar2 = np.array([7,8])
print(np.column_stack((ar1,ar2)))


[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
#vstack 
# last element can be both 1D or 2D array

ar1 = np.array([[1,2,3], [4,5,6]])
ar2 = np.array([7,8,9])
np.vstack((ar1,ar2))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])