#Creating numpy array
#zeros
#ones

In [6]:
#(20,)
import numpy as np

l1 = np.zeros((20,))
print(l1)
l2 = np.ones((20,))
print(l2)
l3 = np.random.randint(1,20,(20,))
print(l3)
# (20,0) => 20 // (20,2) => 20,2
l4 = np.random.rand(20) #rand => from 0 to 1
print(l4)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 3  4  7 13  1  2 11 15  2 13  8 10  2 11  5  3 13 15  1 11]
[0.2084933  0.78244608 0.67161458 0.39363597 0.28643284 0.69161621
 0.69519741 0.35685593 0.32715368 0.33546029 0.46021373 0.05392552
 0.31583343 0.91104384 0.38609597 0.65969447 0.32509384 0.91500151
 0.23561865 0.3290956 ]


In [7]:
# (3,4)
l5 = np.random.randint(1,50,(3,4))
print(l5)

[[ 6 16 18 48]
 [12 24 11 15]
 [30 25 16  6]]


In [8]:
l1 = np.random.rand(3,4)
print(l1)

[[0.19802927 0.69345864 0.33651826 0.00171962]
 [0.23380481 0.93461864 0.98218417 0.1353833 ]
 [0.52682846 0.13889787 0.25457508 0.47167312]]
