In [1]:
#reshape

import numpy as np


ar1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar1.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Convert 1D array to 2D
Number of element should be equal like for 12 it should be 3,4 or 2,6 